spring:
  application:
    name: private-review-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/private_reviews}
    username: ${DB_USERNAME:private_reviews}
    password: ${DB_PASSWORD:private_reviews}
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
